import { GoogleTagManagerHead, GoogleTagManagerBody } from './components/GoogleTagManager'
import GoogleAnalytics from './components/GoogleAnalytics'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  verification: {
    google: 'bshllqo6MIhoBv2oLuo-5lh9FzoXSYWFaQmCOzx62rA',
  },
  robots: {
    index: true,
    follow: true,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <GoogleTagManagerHead />
      </head>
      <body>
        <GoogleTagManagerBody />
        <GoogleAnalytics />
        {children}
      </body>
    </html>
  )
}